name: Testing and building docker image

on:
  push:
    branches: [main]

jobs:
  compile-app:
    runs-on: ubuntu-latest

    steps:
      - name: fetching code
        uses: actions/checkout@v3

      - name: installing dependencies
        run: echo "installing dependencies"
        # Just mocking the installation
        # run: npm install

      - name: running tests
        run: echo "Tests Done"
        # Just mocking the Testing
        # run: npm run test

  docker:
    needs: compile-app
    runs-on: ubuntu-latest
    steps:
      - name: fetching code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/carecapsule:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/carecapsule:${{ github.sha }}
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
